[package]
name = "garden_lang_web"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.89"
garden_lang_parser = { path = "../garden_lang_parser" }

[profile.release]
opt-level = "s"
